package unit

import "strings"

// Model-facing default text. Change it deliberately and raise the version.

// StarterTask is the bundled Profile task.
const StarterTask = "Adapt the character into one Tower Defense Unit from a faithful subset of the supplied source evidence. Plan the character's repertoire and three behaviorally distinct paths before choosing numbers, then implement one automatic base attack and all fifteen purchases with the supported mechanics. Use build codes such as 0-0-0, 3-x-x and 1-2-0. Preserve source ownership and story period, keep behavior the Definition cannot express on the purchase that needs it as a proposed mechanic, and label all numbers and prices as proposals. Do not claim canon verification or balance."

// atlasCapture pins the BTD6 reference values of the default Profile.
const atlasCapture = "btd6-atlas capture 56.3, Steam build 24829026, repository revision a380413 (https://github.com/KyleDerZweite/btd6-atlas/tree/a380413ed809c98654acec7aa37cba40f80bf5c5/data/56.3-build-24829026)"

// defaultRulesSections are the paragraphs of the bundled rules document.
var defaultRulesSections = []string{
	"Design rules and scale references for the BTD6-inspired default Profile. Editable starter rules, not Manga Mayhem rules, BTD6 canon or balance certification. The atlas references below show scale and progression shape; they are not kits to copy.",

	"Purchase roles. The first and second purchase of each path are small readable foundations that stay useful as crosspaths, never a broad all-source damage buff, and what they improve belongs to their path: when one path's early purchases add damage, the other paths' early purchases add something else, while one path may add the same thing twice. The third purchase defines the path, or at least distinguishes it: it adds something that makes the path its own. The identity can be simple, as Dart Monkey's 0-3-0 Triple Shot only throws three darts at once while no other Dart Monkey path throws more than one, or a new form, as Mermonkey's 3-0-0 Abyss Dweller awakens a creature with tentacle attacks. A dimension another path's purchase also raises in passing does not blur it. Larger numbers may come beside that benefit, as Sniper Monkey's 3-0-0 Deadly Precision nearly triples damage and adds +50 damage against Ceramic, but a larger number alone, a targeting change alone or a change with no effect distinguishes nothing. From the third purchase on, a purchase that raises damage also changes how the attack reaches or affects enemies: pierce, attack rate, projectiles, splash, a follow-up, a status, bonus damage against an enemy property, damage type, delivery or the Active Ability, as the scale references show; more range alone does not count. The fourth purchase develops the path's identity, as Mermonkey's 4-0-0 Abyssal Warrior strengthens the tentacles and gives the tridents an ink slow; it need not add a subsystem, and a substantial improvement of one dimension other than damage may qualify when it gives a clear payoff for the price. The fifth purchase is the pinnacle of its path and should feel worth its price: beyond larger numbers it adds a distinct capability, as Mermonkey's 5-0-0 Lord of the Abyss also creates water around itself. Make it a supported behavior where the Definition can express one; a capability it cannot express is a proposed mechanic, which leaves the capstone an unresolved design gap until the Definition supports it. Thousands of Gold for larger numbers alone, the Active Ability's included, is not a pinnacle. Not every purchase needs a new mechanic, and a stat-led path is allowed when its third purchase is its own and its capstone adds a distinct capability.",

	"Match rules. A stationary Unit attacks detected enemies in range along a clear delivery path; detection grants neither delivery nor damage access. Gold is match currency and Health the shared life pool, 150 at the start; Units have no Health. The basic enemy has one layer removed by 1 damage; tougher enemies need explicit rules, and no layer tree or leak simulation exists. Keep damage per hit a whole number in every build, as every reference below does: raise it by whole amounts, preferring +1 to a fraction such as +0.25. Code accepts fractions; this is the Profile's design choice, not a mechanic rule. A player may own one placed 5-x-x, x-5-x or x-x-5 per Unit type and path at a time; the caller enforces this from match state.",

	"Private design checks, never printed in the unit: why a player buys each path, which weakness remains, why a player buys the capstone rather than more fourth-purchase copies (concentration, reach, access or the single placement, not only raw throughput).",

	"Scale references from " + atlasCapture + ". Prices are Medium incremental purchases; files are under game-data/Towers and game-data/Upgrades. Damage per second assumes a target always in range and ignores enemy-class bonuses unless stated. This Profile adapts a bonus against Ceramic as bonus damage against Hardened and a bonus against MOAB-class enemies, such as Bionic Boomerang's +1, as bonus damage against Blimp. The two are separate properties: a Blimp is not Hardened, and a bonus against one never applies to the other. Bonuses against Fortified, Lead or other classes have no counterpart here.",

	"Dart Monkey 0-0-0 (DartMonkey.json): 200 Gold; one dart every 0.95 s at range 32, 1 sharp damage, pierce 2; no Camo detection; sharp damage cannot hurt Lead or Frozen. 1.05 damage per second on one target; one throw deals at most 2 damage in total.",

	"Group capacity, Dart Monkey top (DartMonkey-100 to -500): 1-0-0 Sharp Shots 140, pierce 3. 2-0-0 Razor Sharp Shots 200, pierce 5. 3-0-0 Spike-o-pult 320 replaces the dart with a rebounding spiked ball: 2 damage, pierce 18, every 1.15 s, range 36.8, can hurt Frozen. 4-0-0 Juggernaut 1800: every 1.0 s, pierce 60, can hurt Lead, +3 damage to Ceramic and +2 to Fortified, knockback. 5-0-0 Ultra-Juggernaut 15000: 5 damage, pierce 210, larger Ceramic, Fortified and Lead bonuses; when its pierce runs out the ball splits into two rings of six balls with 2 damage and pierce 50 each. Damage capacity per throw grows 2, 5, 36, 120 and 2250 while single-target damage per second grows only from 1.05 to 5: the branch buys group capacity and access, not ordinary damage.",

	"Precision, Dart Monkey bottom (DartMonkey-001 to -005): 0-0-1 Long Range Darts 90, range 40. 0-0-2 Enhanced Eyesight 200, range 48 and personal Camo detection. 0-0-3 Crossbow 575: 3 damage, pierce 4, range 60. 0-0-4 Sharp Shooter 2050: 6 damage every 0.475 s; every tenth shot is a 50-damage critical. 0-0-5 Crossbow Master 21500: 8 damage every 0.2375 s, pierce 8, range 80, hurts every type; every fifth shot is an 80-damage critical. Counting a critical shot as its critical damage, single-target damage per second is 3.2, about 22 and about 94: each advanced purchase multiplies precise damage and the capstone also adds reach, pierce and access.",

	"Attack speed with an allied active, Dart Monkey middle (DartMonkey-010 to -050): 0-1-0 Quick Shots 100, every 0.8075 s. 0-2-0 Very Quick Shots 190, every 0.6365 s. 0-3-0 Triple Shot 450: three darts in a 30 degree arc every 0.477 s; no top or bottom purchase fires more than one projectile per attack (their files use a SingleEmissionModel, 0-3-0 an ArcEmissionModel of 3). 0-4-0 Super Monkey Fan Club 7200: every 0.239 s; an activated ability for 15 s, recharging in 50 s, turns up to 10 nearby Dart Monkeys with no path above 2 into super monkeys that attack at about 0.063 times their interval. 0-5-0 Plasma Monkey Fan Club 45000: same timing, up to 20 monkeys, +1 damage and +3 pierce on their darts. Darts per second grow 1.05, 1.24, 1.57, 6.3 and 12.6. The 7200 and 45000 prices of x-4-x and x-5-x pay mostly for transforming allied towers, which this Definition cannot express, so they must not price or shape a self-only Active Ability; the Boomerang Monkey and Tack Shooter middle paths below are the self Active references.",

	"Path identity and a pinnacle, Mermonkey top (Mermonkey.json and -100 to -500, and Upgrades/Trident Efficiency.json to Lord of the Abyss.json): tridents every 1.2 s with 2 damage. 1-0-0 Trident Efficiency 150, every 0.96 s. 2-0-0 Trident Swiftness 250, every 0.66 s. 3-0-0 Abyss Dweller 1800 defines the path: the Abyssal Creature awakens with eight tentacle attacks of 8 damage every 3 s, tridents deal 4 damage and nearby Monkeys gain 10 percent pierce. 4-0-0 Abyssal Warrior 4200 develops that form: tentacles deal 12 damage every 2.5 s, tridents coat enemies in an ink that slows them (multiplier 0.6 for 10 s) and the pierce bonus rises to 20 percent. 5-0-0 Lord of the Abyss 23000 is the pinnacle: tentacles deal 50 damage every 1.5 s, the pierce bonus rises to 40 percent, and it creates water within 32 of itself (CreateNearbyWaterModel), which no other Mermonkey path does. The creature, the pierce bonus for allies and the water have no operator here; a purchase that needs such an effect carries it as a proposed mechanic.",

	"Attack speed with a self active, Boomerang Monkey middle (BoomerangMonkey.json and -010 to -050): base 315 Gold, 1 damage every 1.2 s, pierce 4, range 43, returning flight. 0-1-0 Faster Throwing 175, every 0.9 s. 0-2-0 Faster Rangs 250, every 0.6 s. 0-3-0 Bionic Boomerang 1250: every 0.15 s, 8 times the base frequency, and +1 damage to MOAB-class enemies. 0-4-0 Turbo Charge 4200: activated for 10 s, recharging in 45 s: interval times 0.2 and +1 damage. 0-5-0 Perma Charge 35000: permanently every 0.03 s with 4 damage; its active adds 10 damage for 15 s, recharging in 45 s. Single-target damage per second is 0.83, 6.7 at 0-3-0, 67 during the 0-4-0 active (22 percent uptime), 133 permanently at 0-5-0 and 467 during its active. Pierce stays 4, so group capacity grows only through frequency.",

	"Single target with blimp control, Sniper Monkey top (SniperMonkey.json and -100 to -500): base 350 Gold, instant 2 damage every 1.59 s on one target anywhere on the map; no Camo detection; cannot hurt Lead or Frozen. 1-0-0 Full Metal Jacket 350: 4 damage and Lead and Frozen access. 2-0-0 Large Calibre 1300: 7 damage. 3-0-0 Deadly Precision 2200: 20 damage and +50 to Ceramic. 4-0-0 Maim MOAB 6300: 30 damage; each hit immobilizes MOAB-class enemies for 3 s on a MOAB down to 0.75 s on a ZOMG or DDT. 5-0-0 Cripple MOAB 32000: 140 damage, immobilizes for up to 7 s, hit MOAB-class enemies take 5 extra damage per hit, and each hit bursts for 28 damage on up to 10 enemies within 8. Damage per second is 1.3, 2.5, 4.4, 12.6, 18.9 and 88: the fourth purchase adds control access more than damage; the capstone multiplies damage and adds control uptime, vulnerability and a bounded burst.",

	"Control, Ice Monkey top (IceMonkey.json and -100 to -500): base 400 Gold; every 2.4 s it freezes up to 40 non-MOAB enemies within 20 for 1.5 s and deals 1 damage; no Camo detection; cannot hurt Lead or White. 1-0-0 Permafrost 150: frozen enemies keep a 50 percent slow. 2-0-0 Cold Snap 350: can freeze Lead. 3-0-0 Ice Shards 1500: range 25 and a shard effect on frozen enemies. 4-0-0 Embrittlement 2300: also slows MOAB-class enemies and freezes 3 layers instead of 2. 5-0-0 Super Brittle 28000: every 1.56 s, 5 damage, every type, 6 layers. Control exists at the base; purchases add persistence, access and uptime (freeze covers 1.5 s of every 2.4 s, then of every 1.56 s), not ordinary damage.",

	"Knockback (DartMonkey-400 and SuperMonkey-001, KnockbackModel): 4-0-0 Juggernaut pushes enemies back for 0.15 s with multiplier 4 for light enemies, 2 for heavy ones and 0 for MOAB-class; Super Monkey's 0-0-1 Knockback (3,000 Gold) pushes for 0.5 s with 1.25, 0.6 and 0.3. The atlas gives these values, not the movement formula. This Profile's Knockback reads the lifespan as its duration and the light-enemy multiplier as its magnitude, the speed at which the enemy moves back along the track; Blimp and Boss enemies ignore it. It is control: it delays enemies and deals no damage.",

	"Burst active, Tack Shooter middle (TackShooter.json and -010 to -050): base 260 Gold, a ring of 8 tacks every 1.12 s, 1 damage and pierce 1 each, range 23. 0-1-0 Long Range Tacks 100, range 26.9. 0-2-0 Super Range Tacks 225, range 30.8 and pierce 4. 0-3-0 Blade Shooter 550: blades with pierce 8, range 46, can hurt Frozen. 0-4-0 Blade Maelstrom 2700: 2 damage; an activated spin for 3 s, recharging in 20 s, fires 2 blades every 0.045 s with pierce 100 and 2 damage. 0-5-0 Super Maelstrom 15000: 5 damage, +5 to Ceramic, every type; the spin lasts 9 s on the same 20 s recharge. Ring damage capacity per second is 7, 29, 57, 114 and 286; the spin far exceeds it while it lasts, and its uptime rises from 15 to 45 percent.",

	"Support, Monkey Village (MonkeyVillage.json, -100, -200 and -020): base 1200 Gold and no attack; allied towers within 40 gain 10 percent range. 1-0-0 Bigger Radius 400, radius 48. 2-0-0 Jungle Drums 1500, allies attack 15 percent faster. 0-2-0 Radar Scanner 2000, allies in the radius can target Camo. Allied buffs and shared detection have no operator here; a purchase that needs them carries them as proposed mechanics.",

	"Roster shape from the atlas patterns (patterns/towers.md and progression.md): 26 standard towers; primary base prices 200 to 400; tier medians about 200 to 275 for a first purchase, 1500 to 2000 for a third, 4000 to 6500 for a fourth and 30000 to 38000 for a fifth. Final-to-previous purchase price ratios range from 1.58 to 19.64 with median 6.15; they describe prices, not output, and are not a capstone multiplier. The middle fourth purchase carries an ability in 25 of 26 towers and the fifth keeps it; top and bottom fourth purchases show one each. No fifth purchase above changes only ordinary damage.",

	"Health and layer values are starter assumptions. All generated values and prices are proposals that need playtesting.",
}

// defaultRulesText is the bundled rules document text.
var defaultRulesText = strings.Join(defaultRulesSections, "\n\n")

const defaultRulesID = "default-td-profile-v38"
const defaultRulesLocation = "mardwerk-unit:default-td-profile:v38"
const defaultRulesNote = "Bundled starter preset. Edit or replace it in Inputs and rules before preparing a custom Request."
const defaultProfileName = "BTD6-inspired (default)"
const defaultAuthoringRevision = "2026-09-27-atlas-56.3-v38"
